### ISSUE TITLE
Create a readme file

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Regenerator#1]
This is an old project I did for fun to learn web development.
As a first issue I need to add a readme file to this repo.

**Comment by trybick** [comment]
I can do this

**Comment by trybick** [comment]
Any specific content you would like included?

**Comment by eduardconstantin** [comment]
Please add a short description with a picture/gif, contribute section and add [this](https://allcontributors.org/docs/en/bot/installation) markdown for the contributors bot.

**Comment by trybick** [comment]
PR opened #3

**Comment by eduardconstantin** [comment]
@all-contributors please add @trybick  for 📖

**Comment by eduardconstantin** [comment]
https://github.com/all-contributors please add @trybick for doc
