### ISSUE TITLE
Clean style.js file

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Regenerator#14]
The file style.js looks a bit messy, therefor a few things must be done:
- Remove the `Height` function
- Remove window on load resize
- Remove `SETTINGS` object
- Remove timeout used for demo and canvas
- In `audiojs event` replace `getElementsByTagName` with jquery selector
- Remove `main.js` from JS folder and index.html
- Rename `style.js` to `main.js`

**Comment by Devesh326** [comment]
Hey @eduardconstantin I would like to contribute to this.
