### ISSUE TITLE
Clean style.css file

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Regenerator#16]
The file style.css can use some cleaning:
- ~~Remove the canvas at the end of the file~~
- Move audiojs style in a separate file
- Clean and order the rest of the style without breaking anything
- Also remove normalize.css file from CSS folder and index.html

**Comment by Gowrishankar04** [comment]
Hi @eduardconstantin ,

Can you please assign this to me?

Thanks

**Comment by Gowrishankar04** [comment]
Hi @eduardconstantin ,

I have raised PR for the required changes: https://github.com/eduardconstantin/Regenerator/pull/33
Please review and merge it.

Thanks
