### ISSUE TITLE
Create pull request template

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Regenerator#17]
Create a PULL_REQUEST_TEMPLATE.md file to make code validation easier.

A guide can be found [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by jsvigneshkanna** [comment]
Please assign this to my name, wi fix it

**Comment by vishnuvnathan** [comment]
@eduardconstantin Can you assign it to me?
