### ISSUE TITLE
[Feature] Improve UI design

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Regenerator#26]
**Is your feature request related to a problem? Please describe.**
The design doesn't look good at all, it would be nice to change it to something more pleasing.

**Describe the solution you'd like**
An animated gradient for the background similar to the one bellow would be nice to have. The animation has to be slow, something like a wave.
![image](https://user-images.githubusercontent.com/9199763/195681197-f03b2c89-0669-47ea-857b-bdaefc395190.png)

The button may be changed as well, maybe having rounded corners and to fit well with the background.
Probably the font color has to change as well.
Also the loading bar will have to fit with the background.
This [tool](https://webaim.org/resources/contrastchecker/) can be used to check if the contrast is right.

**Comment by amardeep911** [comment]
plz assign this to me

**Comment by amardeep911** [comment]
Plz give the permission to push to the code @eduardconstantin

**Comment by eduardconstantin** [comment]
You need to fork the project and then create a pull request

**Comment by amardeep911** [comment]
@eduardconstantin Plz do consider this

**Comment by amardeep911** [comment]
![image](https://user-images.githubusercontent.com/97588898/195890612-d4847635-6f89-49c6-bf8a-671416decdc3.png)
Gradient fix done
