### ISSUE TITLE
[Feature] Add docker support

### ISSUE THREAD

**Issue by AmreshSinha** [eduardconstantin/Regenerator#38]
**Is your feature request related to a problem? Please describe.**
Using Docker, an app can be hosted on any platform. Currently this app does not have docker support.

**Describe the solution you'd like**
Add docker support by creating `Dockerfile` and `docker-compose.yml`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by eduardconstantin** [comment]
I don't think this needs docker support, but you can add to [this one](https://github.com/eduardconstantin/Crypto-Rankings)
