### ISSUE TITLE
[FEATURE] Replace animation

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Regenerator#39]
**Is your feature request related to a problem? Please describe.**
I would like to improve the UI design and the functionality of this application.
This project started as a joke but I can become something more. I would like to turn this into a relaxation app.

**Describe the solution you'd like**
Instead of the two hands that appear during the animation, I would like to have a flower similar to the one in the picture.
The flower should have an animation that is rotating, growing and shrinking slowly. I think this would be better done using svg.
The background color should be the same blue gradient from the picture.

**Describe alternatives you've considered**
Any suggestion is welcome.

**Additional context**
![image](https://github.com/eduardconstantin/Regenerator/assets/9199763/ba22f943-1c75-42b2-b134-505995acef70)

**Comment by manuelachamoso** [comment]
Can you assign to me this task?

**Comment by vashukashyap** [comment]
i would like to work on this issue! can i work on this?

**Comment by eduardconstantin** [comment]
@vashukashyap I assigned @manuelachamoso because she asked first.

**Comment by vashukashyap** [comment]
ok, no problem sir. can i work on another issue on which she has asked already?

**Comment by manuelachamoso** [comment]
Hello @eduardconstantin, I have a few questions. Would you like the flower in place of the hands that appear at the beginning when you instruct the user to place their hands on the screen? What message would replace it? I added a flower when the music starts, and I removed the loading bar that usually appears. 
![screencapture-127-0-0-1-5500-Regenerator-index-html-2023-10-19-16_09_55](https://github.com/eduardconstantin/Regenerator/assets/89460249/a16e1db1-c16a-4df3-83ab-7c2d49514e17)
Would this suggestion be okay with you? I've attached a photo and a video for you to see (in the video the bar is still not removed, but in the photo it does). [screen-recording (9).webm](https://github.com/eduardconstantin/Regenerator/assets/89460249/4e873a89-279d-49f4-83be-d6e9c4fff00b)

**Comment by eduardconstantin** [comment]
@manuelachamoso you can remove those steps with the messages and the hands after you press the button. The flower should appear after you press the button.
You added the flower as an image? Because I would like it to be made using svg and look similar with the one I attached in the issue.
