### ISSUE TITLE
[FEATURE] Replace song

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Regenerator#40]
**Is your feature request related to a problem? Please describe.**
The current song is not suitable for a relaxation app.

**Describe the solution you'd like**
I would like a song that is similar to the one I attached below, but more soothing and calming.

**Additional context**
https://www.youtube.com/watch?v=N73UWEsXKeU

**Comment by manuelachamoso** [comment]
Can I work in this issue?

**Comment by taran1326** [comment]
Hey , Can you assign me this task ?

**Comment by vashukashyap** [comment]
i would like to work on this issue! can i work on this?

**Comment by kumarharshh** [comment]
Can you assign this issue to me?

**Comment by eduardconstantin** [comment]
You can each create a PR adding a song to the project.
It can be nice to have multiple songs and switch between them.
