### ISSUE TITLE
[BUG] Make UI responsive on smaller screens

### ISSUE THREAD

**Issue by anupjeejo** [eduardconstantin/Regenerator#50]
**Describe the bug**
So the background does not stretch enough on smaller screens.

**To Reproduce**
1. Go to 'inspect element'
2. Click on 'Toggle device tool bar'
3. Select any of the mobile devices
4. See that the site is not responsive

**Expected behavior**
So the UI should be able to adapt to the varying screen sizes.

**Screenshots**
->Screen shots for reference;

Screenshot-1
![Screenshot (56)](https://github.com/eduardconstantin/Regenerator/assets/58913401/f40fb9d4-8791-4c55-8942-0cee1fec129b)

Screenshot-2
![Screenshot (57)](https://github.com/eduardconstantin/Regenerator/assets/58913401/463cce60-e34e-451b-be1d-f093c7e0cfb3)

**Comment by anupjeejo** [comment]
@eduardconstantin , kindly assign me this issue so I can start working on it.
Looking forward to working on this issue, thanks in advance.

**Comment by eduardconstantin** [comment]
hm, yes, this would be a great fix
