### ISSUE TITLE
Clean index.html file

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Regenerator#7]
Javascript code from the end of the document has to be moved in style.js

![image](https://user-images.githubusercontent.com/9199763/195136340-722a2923-a6fa-4af8-8c41-35ebf8f4e2b7.png)
![image](https://user-images.githubusercontent.com/9199763/195136399-2fa6c4cd-e082-4ef0-b93c-31fad1e139d3.png)

**Comment by Pervolarakis** [comment]
can i work on this?

**Comment by eduardconstantin** [comment]
sure
